version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snapStart-app-01"
s3_bucket = "codestar-20230814"
s3_prefix = "snapStart-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
